### ISSUE TITLE
Compiler issues

### ISSUE THREAD

**Issue by dioptre** [sesilio/react-script-loader-hoc#2]
This lib build (npm install) didn't work for me, and I had to extract the original source and put it in my own component for it to work using the default react-scripts published by facebook.

Thanks heaps for the solution though!

**Comment by domlyons** [comment]
Hey there, thanks for posting an issue. Do you have any more information on what is going wrong with the library, such as an error message or details of the browser it is failing in? It sounds to be most likely a babel issue on our end.

**Comment by steadicat** [comment]
FWIW, this is the error I’m getting:

![screen shot 2017-12-13 at 3 48 38 pm](https://user-images.githubusercontent.com/6031/33968513-1ec094f0-e01d-11e7-857f-af25381c898c.png)

**Comment by domlyons** [comment]
Thanks for the info! I've made some changes and tested it and it should work fine now. I'll close this issue for now, let me know if you have any more problems with this.
