### ISSUE TITLE
Remove regenerator runtime

### ISSUE THREAD

**Issue by jaydenseric** [sesilio/react-script-loader-hoc#4]
It looks like the only place async/await syntax is used is here:

https://github.com/sesilio/react-script-loader-hoc/blob/d3d8528172bc01ea3fadbc4d396ab20249429d84/src/index.js#L36

If this were refactored to use regular promise syntax the regenerator runtime dependency could be removed, shaving off 63% of the bundle impact:

https://bundlephobia.com/result?p=react-script-loader-hoc@1.1.0

<img width="956" alt="screen shot 2018-10-12 at 5 37 07 pm" src="https://user-images.githubusercontent.com/1754873/46852093-7d985280-ce45-11e8-8f70-cd059a3a50ff.png">

**Comment by domlyons** [comment]
Hi, thanks for the input. I've made the changes to remove regenerator-runtime in version 1.2.1. Let me know if there are any issues

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/13196852/47571240-00cea380-d930-11e8-8e47-9274ce59496e.png">
