### ISSUE TITLE
React 16.8

### ISSUE THREAD

**Issue by neemah** [sesilio/react-script-loader-hoc#5]
Hello, do you plan to updated dependencies?

**Comment by domlyons** [comment]
What dependencies need to be updated?

PRs are welcome if you see any issues

**Comment by neemah** [comment]
```
"react": "^16.8.4"
```

This is what is needed to use with newest react versions. As for now, upgrading our project to newest react requires to use 2 difference react version (because of react-script-loader-hoc).

Tryed to upgrade and create PR, but with no luck atm :(

**Comment by neemah** [comment]
https://github.com/sesilio/react-script-loader-hoc/pull/7 - please review

**Comment by domlyons** [comment]
Fixed with #7
